### ISSUE TITLE
20150519173350_create_shoppe_product_translation_table.rb error if no seed data

### ISSUE THREAD

**Issue by sennor** [tryshoppe/shoppe#231]
Hi, 

I am just running the rake db:migrate shoppe:setup. 

I get undefined method error because I have no seed data in the database.

**Comment by deanperry** [comment]
If you've got the latest version of Shoppe, you should be able to run `bundle install` and which should have the gem required for that command.

**Comment by sennor** [comment]
In terminal as follows:

`bundle install` ok 
`rails generate shoppe:setup` ok
`rails generate nifty:key_value_store:migration` ok
`rake db:migrate shoppe:setup` fail see error message 

Ruby 2.1.5 and Rails v. 4.2.1 


Error message: 
`Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
test:sexyshades pcoe$ rake db:migrate shoppe:setup
== 20150519173350 CreateShoppeProductTranslationTable: migrating ==============
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `create_translation_table!' for #<Class:0x007fa4bbc02e90>/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/shoppe-1.1.0/db/migrate/20150519173350_create_shoppe_product_translation_table.rb:3:in `up'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:609:in `exec_migration'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/pcoe/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/pcoe/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
NoMethodError: undefined method `create_translation_table!' for #<Class:0x007fa4bbc02e90>
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/shoppe-1.1.0/db/migrate/20150519173350_create_shoppe_product_translation_table.rb:3:in `up'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:609:in `exec_migration'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/pcoe/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/pcoe/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
test:sexyshades pcoe$ rake db:migrate shoppe:setup
== 20150519173350 CreateShoppeProductTranslationTable: migrating ==============
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `create_translation_table!' for #<Class:0x007fcce57aaee0>/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/shoppe-1.1.0/db/migrate/20150519173350_create_shoppe_product_translation_table.rb:3:in `up'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:609:in `exec_migration'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/pcoe/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/pcoe/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
NoMethodError: undefined method `create_translation_table!' for #<Class:0x007fcce57aaee0>
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/shoppe-1.1.0/db/migrate/20150519173350_create_shoppe_product_translation_table.rb:3:in `up'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:609:in `exec_migration'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/pcoe/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/pcoe/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
test:sexyshades pcoe$ rake db:migrate shoppe:setup
== 20150519173350 CreateShoppeProductTranslationTable: migrating ==============
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `create_translation_table!' for #<Class:0x007fe514f519e0>/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/shoppe-1.1.0/db/migrate/20150519173350_create_shoppe_product_translation_table.rb:3:in `up'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:609:in `exec_migration'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/pcoe/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/pcoe/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
NoMethodError: undefined method `create_translation_table!' for #<Class:0x007fe514f519e0>
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/shoppe-1.1.0/db/migrate/20150519173350_create_shoppe_product_translation_table.rb:3:in `up'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:609:in `exec_migration'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/pcoe/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/pcoe/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/pcoe/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate`

**Comment by deanperry** [comment]
What version of Shoppe are you using?

**Comment by sennor** [comment]
Shoppe version 1.1.0. Think the error is caused by the globalize gem.. Which globalize version are you locked on?

**Comment by sennor** [comment]
Switched back to using Shoppe version 1.0.7 which works fine.

**Comment by deanperry** [comment]
hmm ok. What if you try and update to Rails 4.2.3?

On 13 July 2015 at 20:06, sennor <notifications@github.com> wrote:

> Switched back to using Shoppe version 1.0.7 which works fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tryshoppe/shoppe/issues/231#issuecomment-121024643>.
>



-- 
Kind Regards,
Dean Perry

http://deanpcmad.com
@DeanPerry <https://twitter.com/DeanPerry>

**Comment by sennor** [comment]
Updated to Rails 4.2.3 get the same error

**Comment by deanperry** [comment]
OK. I'll probably be moving the translation code into a separate gem

sennor wrote:
