### ISSUE TITLE
rake shoppe:seed:  ActiveRecord::RecordInvalid: Validation failed: Permalink has already been taken

### ISSUE THREAD

**Issue by chricri** [tryshoppe/shoppe#292]
i have this error with rake shoppe:seed when "i setting up shoppe" for the first time... please help me

```
$ rake shoppe:seed --trace
** Invoke shoppe:seed (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute shoppe:seed
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Permalink has already been taken

c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/acti
ve_record/validations.rb:57:in `save!'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/acti
ve_record/attribute_methods/dirty.rb:29:in `save!'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/acti
ve_record/transactions.rb:273:in `block in save!'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/acti
ve_record/transactions.rb:329:in `block in with_transaction_returning_status'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/acti
ve_record/connection_adapters/abstract/database_statements.rb:201:in `block in t
ransaction'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/acti
ve_record/connection_adapters/abstract/database_statements.rb:209:in `within_new
_transaction'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/acti
ve_record/connection_adapters/abstract/database_statements.rb:201:in `transactio
n'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/acti
ve_record/transactions.rb:208:in `transaction'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/acti
ve_record/transactions.rb:326:in `with_transaction_returning_status'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/acti
ve_record/transactions.rb:273:in `save!'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/acti
ve_record/validations.rb:41:in `create!'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/shoppe-1.1.1/db/seeds.rb:20
:in `<top (required)>'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/act
ive_support/dependencies.rb:247:in `require'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/act
ive_support/dependencies.rb:247:in `block in require'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/act
ive_support/dependencies.rb:232:in `load_dependency'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/act
ive_support/dependencies.rb:247:in `require'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/shoppe-1.1.1/lib/tasks/shop
pe.rake:5:in `block (2 levels) in <top (required)>'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.r
b:240:in `call'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.r
b:240:in `block in execute'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.r
b:235:in `each'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.r
b:235:in `execute'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.r
b:179:in `block in invoke_with_call_chain'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.r
b:172:in `invoke_with_call_chain'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.r
b:165:in `invoke'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/applic
ation.rb:150:in `invoke_task'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/applic
ation.rb:106:in `block (2 levels) in top_level'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/applic
ation.rb:106:in `each'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/applic
ation.rb:106:in `block in top_level'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/applic
ation.rb:115:in `run_with_threads'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/applic
ation.rb:100:in `top_level'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/applic
ation.rb:78:in `block in run'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/applic
ation.rb:176:in `standard_exception_handling'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/applic
ation.rb:75:in `run'
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in
`<top (required)>'
c:/RailsInstaller/Ruby2.1.0/bin/rake:23:in `load'
c:/RailsInstaller/Ruby2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => shoppe:seed
```

**Comment by distortia** [comment]
I am also experiencing this issue

**Comment by deanperry** [comment]
Is this just when running shoppe:seed? What version of Shoppe are you using?

**Comment by chricri** [comment]
Yes also when running shoppe:seed.....I'm using the version 1.1.1...

**Comment by chrztoph** [comment]
#300
