### ISSUE TITLE
Error on Shoppe Setup

### ISSUE THREAD

**Issue by everestlab** [tryshoppe/shoppe#313]
Hi, i want to try Shoppe but having this error on command rails generate shoppe:setup

Ruby version 2.2.3
Rails version 4.2.5 on OS X El Capitan

Thanks for your help!
```
/Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- net/ssh (LoadError)
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fog-1.31.0/lib/fog/joyent/compute.rb:3:in `<top (required)>'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fog-1.31.0/lib/fog/joyent.rb:1:in `<top (required)>'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fog-1.31.0/lib/fog.rb:41:in `<top (required)>'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/storage/fog.rb:3:in `<top (required)>'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/storage.rb:9:in `<top (required)>'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave.rb:78:in `<top (required)>'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoppe-1.1.1/lib/shoppe.rb:14:in `<top (required)>'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /Users/vinamelody/Code/shop/config/application.rb:7:in `<top (required)>'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/application.rb:82:in `require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/application.rb:82:in `preload'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/application.rb:143:in `serve'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/application.rb:131:in `block in run'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/application.rb:125:in `loop'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/application.rb:125:in `run'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/vinamelody/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by deanperry** [comment]
This seems to be an issue with the latest version of `fog`. I've pushed `v1.1.2` which fixes it

**Comment by everestlab** [comment]
Hi Dean, is there anything that I need to do or change to pull version 1.1.2 ?

**Comment by deanperry** [comment]
Just do `bundle update shoppe` :)

**Comment by everestlab** [comment]
Aha, great, it works like magic now! time to play around :)
Thanks a lot!
