### ISSUE TITLE
Shoppe + Refinery CMS Actionpack RuntimeError

### ISSUE THREAD

**Issue by mark-orussa** [tryshoppe/shoppe#342]
I've been trying to get some combination of Shoppe + [https://github.com/refinery/refinerycms](https://github.com/refinery/refinerycms) working together for awhile now. I've managed to get past gem dependency issues and have Refinery CMS working. When I try install Shoppe by running

`rails generate shoppe:setup`

I get this error:
<pre>Error:[rake --tasks] /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/stack.rb:112:in `push': can't modify frozen Array (RuntimeError)
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/stack.rb:112:in `use'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/shoppe-1.1.2/lib/shoppe/engine.rb:30:in `block in <class:Engine>'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
	from /Users/username/Sites/markorussa.dev/refinery/config/environment.rb:5:in `<top (required)>'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/application.rb:92:in `preload'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/application.rb:143:in `serve'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/application.rb:131:in `block in run'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/application.rb:125:in `loop'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/application.rb:125:in `run'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/username/.rbenv/versions/2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'</pre>

Here is my gemfile:
<pre>source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
# Use sqlite3 as the database for Active Record
group :development, :test do
  gem 'sqlite3'
end
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem 'refinerycms', '~> 3.0', '>= 3.0.1'
gem 'refinerycms-authentication-devise', '~> 1.0.4'
gem 'refinerycms-blog', git: 'https://github.com/refinery/refinerycms-blog', branch: 'master'
gem 'refinerycms-settings'
gem 'refinerycms-inquiries', '~> 3.0.0'

gem 'shoppe', '~> 1.0'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end</pre>

I've seen others on the interwebs mention a similar problem ([https://github.com/intridea/omniauth/issues/751](https://github.com/intridea/omniauth/issues/751)), but not with Shoppe and I can't figure out a solution for it. It might be simple, but I'm still fairly new to Rails.

I'd really like to have Refinery and Shoppe play together and not have to separate them on separate subdomains or something like that.

**Comment by deanpcmad** [comment]
Does setting the gem location to github: "tryshoppe/shoppe" fix the issue?
