### ISSUE TITLE
Shoppe not rendering the login page instead gives an error in production

### ISSUE THREAD

**Issue by kizzonia** [tryshoppe/shoppe#416]
`2016-12-31T03:32:32.505676+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5/lib/action_view/rendering.rb:83:in `render_to_body'
2016-12-31T03:32:32.505680+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
2016-12-31T03:32:32.505681+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
2016-12-31T03:32:32.505682+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/abstract_controller/rendering.rb:25:in `render'
2016-12-31T03:32:32.505682+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_controller/metal/rendering.rb:16:in `render'
2016-12-31T03:32:32.505683+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
2016-12-31T03:32:32.505684+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
2016-12-31T03:32:32.505685+00:00 app[web.1]:   vendor/ruby-2.2.6/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
2016-12-31T03:32:32.505685+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/core_ext/benchmark.rb:12:in `ms'
2016-12-31T03:32:32.505689+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
2016-12-31T03:32:32.505690+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
2016-12-31T03:32:32.505691+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:43:in `render'
2016-12-31T03:32:32.505690+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
2016-12-31T03:32:32.505692+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
2016-12-31T03:32:32.505693+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/abstract_controller/base.rb:198:in `process_action'
2016-12-31T03:32:32.505692+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
2016-12-31T03:32:32.505694+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_controller/metal/rendering.rb:10:in `process_action'
2016-12-31T03:32:32.505694+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
2016-12-31T03:32:32.505695+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
2016-12-31T03:32:32.505696+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
2016-12-31T03:32:32.505696+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
2016-12-31T03:32:32.505697+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
2016-12-31T03:32:32.505698+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
2016-12-31T03:32:32.505698+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
2016-12-31T03:32:32.505699+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
2016-12-31T03:32:32.505700+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
2016-12-31T03:32:32.505719+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/abstract_controller/callbacks.rb:19:in `process_action'
2016-12-31T03:32:32.505720+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_controller/metal/rescue.rb:29:in `process_action'
2016-12-31T03:32:32.505721+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
2016-12-31T03:32:32.505722+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `block in instrument'
2016-12-31T03:32:32.505722+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2016-12-31T03:32:32.505723+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `instrument'
2016-12-31T03:32:32.505724+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
2016-12-31T03:32:32.505724+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
2016-12-31T03:32:32.505725+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/abstract_controller/base.rb:137:in `process'
2016-12-31T03:32:32.505725+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
2016-12-31T03:32:32.505726+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5/lib/action_view/rendering.rb:30:in `process'
2016-12-31T03:32:32.505727+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_controller/metal.rb:196:in `dispatch'
2016-12-31T03:32:32.505731+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
2016-12-31T03:32:32.505732+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_controller/metal.rb:237:in `block in action'
2016-12-31T03:32:32.505732+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:76:in `call'
2016-12-31T03:32:32.505737+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:45:in `serve'
2016-12-31T03:32:32.505733+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
2016-12-31T03:32:32.505740+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/railtie.rb:194:in `method_missing'
2016-12-31T03:32:32.505738+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `serve'
2016-12-31T03:32:32.505738+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `each'
2016-12-31T03:32:32.505739+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:518:in `call'
2016-12-31T03:32:32.505741+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/mapper.rb:51:in `serve'
2016-12-31T03:32:32.505740+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/railtie.rb:194:in `public_send'
2016-12-31T03:32:32.505739+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:817:in `call'
2016-12-31T03:32:32.505737+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:43:in `block in serve'
2016-12-31T03:32:32.505741+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:43:in `block in serve'
2016-12-31T03:32:32.505742+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `each'
2016-12-31T03:32:32.505742+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `serve'
2016-12-31T03:32:32.505743+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:817:in `call'
2016-12-31T03:32:32.505745+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/nifty-attachments-1.0.4/lib/nifty/attachments/middleware.rb:23:in `call'
2016-12-31T03:32:32.505744+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/shoppe-1.1.2/lib/shoppe/settings_loader.rb:10:in `call'
2016-12-31T03:32:32.505745+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
2016-12-31T03:32:32.505746+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
2016-12-31T03:32:32.505747+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
2016-12-31T03:32:32.505747+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/etag.rb:24:in `call'
2016-12-31T03:32:32.505748+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/conditionalget.rb:25:in `call'
2016-12-31T03:32:32.505749+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
2016-12-31T03:32:32.505749+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/flash.rb:260:in `call'
2016-12-31T03:32:32.505749+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
2016-12-31T03:32:32.505750+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
2016-12-31T03:32:32.505751+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
2016-12-31T03:32:32.505751+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/cookies.rb:560:in `call'
2016-12-31T03:32:32.505752+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/query_cache.rb:36:in `call'
2016-12-31T03:32:32.505752+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
2016-12-31T03:32:32.505753+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
2016-12-31T03:32:32.505753+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
2016-12-31T03:32:32.505754+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
2016-12-31T03:32:32.505755+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
2016-12-31T03:32:32.505755+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2016-12-31T03:32:32.505756+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
2016-12-31T03:32:32.505756+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
2016-12-31T03:32:32.505757+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2016-12-31T03:32:32.505757+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:38:in `call_app'
2016-12-31T03:32:32.505761+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `block in call'
2016-12-31T03:32:32.505762+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `block in tagged'
2016-12-31T03:32:32.505762+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:26:in `tagged'
2016-12-31T03:32:32.505763+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `tagged'
2016-12-31T03:32:32.505763+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `call'
2016-12-31T03:32:32.505764+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/request_id.rb:21:in `call'
2016-12-31T03:32:32.505765+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
2016-12-31T03:32:32.505765+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'
2016-12-31T03:32:32.505766+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2016-12-31T03:32:32.505766+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/static.rb:116:in `call'
2016-12-31T03:32:32.505767+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
2016-12-31T03:32:32.505767+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:518:in `call'
2016-12-31T03:32:32.505768+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/application.rb:165:in `call'
2016-12-31T03:32:32.505768+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-3.6.2/lib/puma/configuration.rb:225:in `call'
2016-12-31T03:32:32.505769+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-3.6.2/lib/puma/server.rb:578:in `handle_request'
2016-12-31T03:32:32.505770+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-3.6.2/lib/puma/server.rb:415:in `process_client'
2016-12-31T03:32:32.505770+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-3.6.2/lib/puma/server.rb:275:in `block in run'
2016-12-31T03:32:32.505771+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-3.6.2/lib/puma/thread_pool.rb:116:in `call'
2016-12-31T03:32:32.505771+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-3.6.2/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
2016-12-31T03:32:32.505772+00:00 app[web.1]:
2016-12-31T03:32:32.505773+00:00 app[web.1]:
2016-12-31T03:32:33.043421+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=beadpalace.herokuapp.com request_id=427e2a8a-ec1d-4858-a697-97f2960c0c76 fwd="197.210.28.150" dyno=web.1 connect=1ms service=2ms status=304 bytes=48

c:\Sites\BeadPalace>`

**Comment by kizzonia** [comment]
Everything is set  completely 

i am confused if installing devise was the issue

pls i need a rely ASAP

**Comment by kizzonia** [comment]
it wrks perfectly in development

**Comment by kizzonia** [comment]
Just solved it had to remove turbolinks and precompiling
